language: node_js

sudo: false

branches:
  only:
    - TR

env:
  global:
    - URL="https://rawgit.com/w3c/mediacapture-depth/TR/ECHIDNA"
    - DECISION="https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html"
    - secure: "NOnRV3zs4zT3OFN5lSnuzc//VxvRKcUmGH/4YPQM2Xqm/LorP4D35GtREJL3o/n273CxyCV6IRtx/LPOSQQymZVSwfMHfIB+QA+llaGw6eItVGq0thxXGncXv5z8L6XV6cT7B0Y5UEK5GaHUdzyCHT5L8YvnadeXlVsASBAMinI="
 
script:
  - echo "ok"

after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
