language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="https://w3c.github.io/requestidlecallback/W3CTRMANIFEST"
  - DECISION="http://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - secure: "XGm6mMnQvgHAK6L8tilahUHGFoyPViHJ8SJt9g7aXIoWkb3S1xcPawGkwI/jES7FTbfsZkiH3R9xf93pvMEn+Yy60nhOLLW/b/5ibl9qaxr9kShVy4+XrMkWdlTz5W7W4X9wvguH8AEAU+aYL7otqzgQltGsj0jbeviH7hVH+no8iIgm65Uwzo1Fi3D3y4gyKKquYFOlNXdyZhFuE2bIiiE4HJxeJd39BY5FmX8weX0paTt8A14UXMt48MP+R6fq3bD9N0xTmBjSWo2TfiXgcebW769wmJvhSpjUBqk4YllLBdNFx2Q2fTCaAwj2d76YtQMuROzgHMRarqs4QhupPGnPOaw28U1AOUspJJ5+xvlEQFtxDeH8E3QOaeWTiD1a7KBh4EDoUcvnPW7jlDHhW7TESQDeo9txeucEMlMdFhWE4/yawJ/iSwamS5nqlp6e4cYF4NVVYDv7eeGYmjkj55OOr9UqBgZSnYbIiQz/cZHQTYwesuj7gU+RU4oCvkan+41+jWK4eqg6JKzbPtLNqlg74FT+vXzZbqzYOTI7BxFBfDOu3la0u+HfrEMujcInWZRCcqUhcS8uDMy8FInRQhkAk2qD+1ji45JFMgF3aaBysCI73DvnbAMvxVQ3NEUlQFtdiPSt6pdKOHO8UjrOtUceL+wHDWOIgJgGMq44Ji0="
script:
- echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'
