# .github/workflows/epub-a11-tech-11.yml
name: CI (EPUB EU Accessibility Act Mapping)
on:
  pull_request:
    paths: 
      - "epub33/epub-a11y-eaa-mapping/**"
      - "epub33/common/**"
  push:
    branches: [main]
    paths: 
      - "epub33/epub-a11y-eaa-mapping/**"
      - "epub33/common/**"
jobs:
  main:
    name: Publish EPUB Accessibility - EU Accessibility Act Mapping 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub33/epub-a11y-eaa-mapping/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_A11Y_EAA_MAPPING }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-18-epub#resolution2
          W3C_BUILD_OVERRIDE: |
             shortName: epub-a11y-eaa-mapping
             specStatus: NOTE
