# .github/workflows/epub-multi-rend-11.yml
name: CI (EPUB SSV)
on:
  pull_request:
    paths: 
      - "epub33/ssv/**"
      - "epub33/common/**"
  push:
    branches: [main]
    paths: 
      - "epub33/ssv/**"
      - "epub33/common/**"
jobs:
  main:
    name: Publish Structural Semantics Vocabulary 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub33/ssv/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_SSV }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-10-14-epub#resolution1
          W3C_BUILD_OVERRIDE: |
             shortName: epub-ssv-11
             specStatus: NOTE
