language: node_js
node_js:
  - "6"
  - "8"
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: web-human@w3.org
  api_key:
    secure: WIAmYrzBUt+mne5AGN3FojGUBLVaC+kBg0Uwz3h/nkSeDZZe7afBGVrRYigoBZKGJ43xciqOe3OFYG2T/EayUHxk17jaIIwP7cG3rLBihCQzDZqKXQV//78X0LhYwfty+FwBVqZJrbBj/RqW02LKZN/lIhwuNek0F/DQL0wFoZM=
  on:
    tags: true
    repo: w3c/third-party-resources-checker
