# Site settings
title: "How to Meet WCAG (Quickref Reference)"
email: ee@w3.org
description: ""
baseurl: "/wai-wcag-quickref" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
status: draft
version: "3.5.1"

techniqueurl: https://www.w3.org/WAI/WCAG21/Techniques/
understandingurl: https://www.w3.org/WAI/WCAG21/Understanding/

port: 4099

safe: true
lsi: false

# Build settings
markdown: kramdown

repository: 'w3c/wai-wcag-quickref'

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false

collections:
  filters:
    output: false
  help:
    output: false


plugins:
  - jekyll-github-metadata

exclude:
  - node_modules
  - .sass-cache
  - Gemfile.lock
  - Gemfile
  - gulpfile.js
  - npm-debug.log
  - package.json
  - questions.md
  - w3c.json
  - package-lock.json
  - text.html
  - README.md
  - pnpm-lock.yaml
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
