sudo: false
language: ruby

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake deploy

env:
  global:
    - secure: "Oe4THt/DxGs9opppWiDP9rs3OaIkm2hYF2z66WVcdMcW56zxegO5sRqlturEEbcOX4rQxtOqVc32yaMRJQvMjfyq2W7Dw+jzttbZlvlgqVUCjErjY6SovH9afjSc6Gy9c3aIN8zcBQcpQfNxC1r7Td4eDEkwzbTj56zaUjcd3+0="

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'