language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by vnu.jar

notifications:
  email:
    on_success: never

branches:
  only:
    - gh-pages
    - /.*/

install:
  - pip install html5validator

script:
  - ./misc/scripts/validate-html.sh
