language: node_js
node_js:
- node
cache:
  npm: false
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: 8a84087ed6cb
  - COMMIT_AUTHOR_EMAIL: plh+deploy@w3.org
  - W3C_API_KEY: pnvbbs930w0wkkckowww0sk0wocow0k
