language: ruby
rvm:
  - 2.2.3
script:
  - bundle exec htmlproof ./index.html --check-html
  - bundle exec htmlproof ./publishing-snapshots/REC-csv2json/Overview.html --check-html
  - bundle exec htmlproof ./publishing-snapshots/REC-csv2rdf/Overview.html --check-html
  #- bundle exec htmlproof ./publishing-snapshrts/REC-html-note/Overview.html --check-html
  - bundle exec htmlproof ./publishing-snapshots/REC-metadata/Overview.html --check-html
  #- bundle exec htmlproof ./publishing-snapshrts/REC-ns/Overview.html --check-html
  - bundle exec htmlproof ./publishing-snapshots/REC-syntax/Overview.html --check-html
  - bundle exec htmlproof ./ns/index.html --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer