password_strength_test:
    pattern: /
    defaults: { _controller: W3CPasswordStrengthBundle:Default:index, _format: json, _method: GET }
    requirements:
        _schemes: https
        _method: GET
    options:
        expose: true
